geoblacklight/geoblacklight.github.io

Gemfile
_config.yml
_includes/header.html
_layouts/tutorial-c4l.html
_layouts/tutorial.html
_posts/2015-02-09-a-hands-on-introduction-to-geoblacklight.markdown
_posts/2015-02-09-create-your-application.markdown
_posts/2015-02-09-geoblacklight-overview.markdown
_posts/2015-02-09-index-solr-documents.markdown
_posts/2015-02-09-setting-up-your-environment.markdown
_sass/_application.scss
_sass/_article.scss
_sass/_flash.scss
_sass/_syntax_highlighting.scss
_sass/base/_lists.scss
blog.html
css/main.scss
tutorials.html

- Adds in Tutorial area of site
- Adds Code4Lib tutorials
- Updates some styles, code blocks and flash

initial commit for code4lib workshop

---

_posts/2015-02-09-setting-up-your-environment.markdown

A big thanks to Zach Vowell for sharing his experience and creating this guide.

add in contributed windows guide

---

Gemfile
_config.yml
_posts/2015-02-05-using-geocombine-to-harvest-and-index-opengeometadata.markdown
_posts/2015-02-09-create-your-application.markdown
_posts/2015-02-09-customize-your-application.markdown
_posts/2015-02-09-geoblacklight-overview.markdown
_posts/2015-02-09-index-solr-documents.markdown
_posts/2015-02-09-setting-up-your-environment.markdown
_sass/_article.scss
_sass/_syntax_highlighting.scss

Still in progress... need to address some styling and markup issues with some code blocks still.

change from redcarpet to kramdown

---

_includes/header.html
_sass/_application.scss
connect.html

Adds various ways to connect to the project.

Add Connect page to GeoBlacklight site.

---

.gitignore
.travis.yml
script/cibuild

Basic checking if the jekyll site will build

adds support for ci build

---

.travis.yml
_posts/2015-02-09-create-your-application.markdown

update to recommended task

---

_posts/2015-02-09-geoblacklight-overview.markdown

Following up with documentation from https://github.com/geoblacklight/geoblacklight/pull/461

Adds description for data-dictionary term in dct_references_s

---

_includes/footer.html

Thanks @bess for the feedback!

update footer to send to webpage instead of mailto

---

_data/showcase.yml

Updates digital initiatives url to correct value.

Update URL for Lewis and Clark

---

.travis.yml
_config.yml

From this comment: https://github.com/jekyll/jekyll/issues/5267#issuecomment-349295326
Fixes #95

Travis CI: try the exclude: [vendor] fix

---

_posts/2015-02-09-customize-your-application.markdown
_posts/2015-02-09-index-solr-documents.markdown

Updates to make tutorial compatible with GeoBlacklight 2.0.

Update tutorial for GeoBlacklight 2.0

---

_posts/2019-02-01-winter-code-sprint-version-2.md

Create 2019-02-01-winter-code-sprint-version-2.md

Short blog post for the codesprint & GBL 2.0

---

_posts/2015-02-09-setting-up-your-environment.markdown

Adds Node.js LTS and Yarn as dependencies for the development environment in the GeoBlacklight tutorial.

Adds to the documentation how and from where to install JavaScript runtimes

---

.gitignore
connect.html
functions/slack-signup.js
functions/submission-created.js
netlify.toml
package-lock.json
package.json
slack-signup.html

This PR adds a form coupled with Netlify lambda functions will automate our Slack signups. It does use an undocumented Slack API but seems to be the way everyone else does this.

Setup basic netlify functions

---

README.md
_includes/header.html
_projects/geoblacklight-icons/index.markdown
_projects/openindexmaps/index.markdown
about.md
connect.html
index.html

This PR is a first-pass effort at carving out a space on GeoBlacklight.org to display community roles, technical values, and a project roadmap. This starts work gestured at in our community conversations and in #120 
Everything is subject to review!

first pass at community structure

---

_includes/header.html
about.md

Per our discussion in today's community meeting, here is a request that recognizes Karen as the community coordinator and points to other roles and values that are forthcoming. Open for suggested changes to wording!

Recognize karen

---

_includes/header.html
about.md

This reverts commit c2c1e5efdebdd388752de97075f5e853bf20abd4.
This will enable the about page things proposed in https://github.com/geoblacklight/geoblacklight.github.io/pull/121

Revert "preserves website changes but pauses about page"

---

_posts/2020-09-15-summer-sprint-2020.md

Quick pass at a blog post. May have errors.

Summer sprint 2020

---

_projects/geoblacklight-schema/index.markdown

This adds the Metadata Workgroup to the bottom of the Metadata Schema page.

Metadata wg

---

_posts/2021-02-10-announcing-winter-sprint-2021.md

Winter 2021 sprint announcment

---

_projects/geoblacklight-schema/index.markdown

Adds 2 members and includes institutional affiliation

updated workgroup membership

---

_posts/2015-02-09-create-your-application.markdown
_posts/2015-02-09-customize-your-application.markdown
_posts/2015-02-09-geoblacklight-overview.markdown
_posts/2015-02-09-setting-up-your-environment.markdown
index.html

This pull request aims to update the tutorial to work with the current version of GeoBlacklight.
Requires: https://github.com/geoblacklight/geoblacklight/pull/998

Modernize GeoBlacklight tutorial

---

about.md

These are the proposed updates to the About GeoBlacklight page. Thanks!

updating About GeoBlacklight page

---

about.md

removing the no-longer-needed bulleted list after accidentally doing this from the wrong branch earlier

Update about.md hopefully for real this time

---

about.md
connect.html

Updates remaining links to Wiki or GitHub repos with opengeometadata.org

use opengeometadata.org for links

---

guides/upgrading.md

Expanded with additional details and code snippets.

GBLv4 Upgrade Notes

---

.github/workflows/pages.yml

Add GitHub Actions workflow for Pages deployment

---

connect.html

Fixes second Slack signup link.

Update Chat on Slack link

---

docs/about.md

update contributor list

---

docs/docs/developers.md

Updated to reflect https://github.com/geoblacklight/geoblacklight/pull/1450

Update developer docs for running Solr and rails separately

---

docs/docs/solr_search_relevancy.md
mkdocs.yml

New page for search relevancy
